# Generated by Django 3.2.5 on 2021-10-24 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_fiscalia', models.CharField(max_length=5)),
                ('letra', models.CharField(max_length=1)),
                ('año', models.DateField(auto_now=True)),
                ('tribunal', models.CharField(max_length=2)),
                ('numero_expediente', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('DE', 'DEMANDADO'), ('DD', 'DEMANDANTE'), ('FF', 'FISCAL'), ('JZ', 'JUEZ'), ('AD', 'ABOGADO DEFENSOR'), ('SE', 'SECRETARIO DEFENSOR'), ('TE', 'TESTIGO')], help_text='Rol del usuario en el caso', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonasIntervenientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incluido', models.DateField(auto_now=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juris.expediente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juris.profile')),
            ],
        ),
        migrations.AddField(
            model_name='expediente',
            name='intervenientes',
            field=models.ManyToManyField(through='juris.PersonasIntervenientes', to='juris.Profile'),
        ),
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=200)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juris.expediente')),
            ],
        ),
    ]
