# Generated by Django 3.2.5 on 2021-10-27 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_fiscalia', models.CharField(max_length=5)),
                ('letra', models.CharField(max_length=1)),
                ('año', models.DateField(auto_now=True)),
                ('tribunal', models.CharField(max_length=2)),
                ('numero_expediente', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PersonasIntervenientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incluido', models.DateField(auto_now=True)),
                ('rol', models.CharField(choices=[('DE', 'DEMANDADO'), ('DD', 'DEMANDANTE'), ('FF', 'FISCAL'), ('JZ', 'JUEZ'), ('AD', 'ABOGADO DEFENSOR'), ('SE', 'SECRETARIO DEFENSOR'), ('TE', 'TESTIGO'), ('PE', 'PERSONA EXTRA')], default='PE', help_text='Rol del usuario en el caso', max_length=2)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juris.expediente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rol', 'expediente')},
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='intervenientes',
            field=models.ManyToManyField(through='juris.PersonasIntervenientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Expediente actualizado', max_length=30)),
                ('contenido', models.CharField(max_length=200)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('expediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='juris.expediente')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='expediente',
            unique_together={('numero_de_fiscalia', 'letra', 'tribunal', 'numero_expediente')},
        ),
    ]
