# Generated by Django 3.2.5 on 2021-10-29 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de conclusión')),
                ('prosecutor_number', models.CharField(max_length=5, verbose_name='número de fiscalía')),
                ('court_number', models.CharField(max_length=2, verbose_name='número del tribunal')),
                ('record_number', models.CharField(max_length=6, verbose_name='número de expediente')),
                ('letter', models.CharField(max_length=1, verbose_name='letra')),
                ('termination_reason', models.CharField(blank=True, max_length=100, verbose_name='motivo de conclusión')),
                ('summary', models.CharField(blank=True, max_length=100, verbose_name='resumen del caso')),
            ],
            options={
                'verbose_name': 'expediente',
                'verbose_name_plural': 'expedientes',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEF', 'Acusado'), ('PLA', 'Demandante')], max_length=3, verbose_name='Tipo')),
                ('legal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juris.legalrecord')),
            ],
            options={
                'verbose_name': 'Parte',
                'verbose_name_plural': 'Partes',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('identity_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LE', 'Legal'), ('NA', 'Natural')], default='NA', max_length=2)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100, verbose_name='resumen')),
                ('date', models.DateField(verbose_name='fecha de ingreso')),
                ('type', models.CharField(max_length=100, verbose_name='fecha de ingreso')),
                ('legal_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='juris.legalrecord')),
            ],
            options={
                'verbose_name': 'actuación judicial',
                'verbose_name_plural': 'actuaciones judiciales',
            },
        ),
        migrations.AlterUniqueTogether(
            name='expediente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='intervenientes',
        ),
        migrations.AlterUniqueTogether(
            name='personasintervenientes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='personasintervenientes',
            name='expediente',
        ),
        migrations.RemoveField(
            model_name='personasintervenientes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Actualizacion',
        ),
        migrations.DeleteModel(
            name='Expediente',
        ),
        migrations.DeleteModel(
            name='PersonasIntervenientes',
        ),
        migrations.AddField(
            model_name='part',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juris.person'),
        ),
        migrations.AddField(
            model_name='legalrecord',
            name='parts',
            field=models.ManyToManyField(related_name='legal_records', through='juris.Part', to='juris.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('person', 'type', 'legal_record')},
        ),
        migrations.AlterUniqueTogether(
            name='legalrecord',
            unique_together={('prosecutor_number', 'court_number', 'record_number', 'letter')},
        ),
    ]
