# Generated by Django 3.2.5 on 2021-10-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rol',
        ),
        migrations.AddField(
            model_name='personasintervenientes',
            name='rol',
            field=models.CharField(choices=[('DE', 'DEMANDADO'), ('DD', 'DEMANDANTE'), ('FF', 'FISCAL'), ('JZ', 'JUEZ'), ('AD', 'ABOGADO DEFENSOR'), ('SE', 'SECRETARIO DEFENSOR'), ('TE', 'TESTIGO'), ('PE', 'PERSONA EXTRA')], default='PE', help_text='Rol del usuario en el caso', max_length=2),
        ),
    ]
