# Generated by Django 3.2.5 on 2021-10-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0002_auto_20211024_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='titulo',
            field=models.CharField(default='Expediente actualizado', max_length=30),
        ),
    ]
