# Generated by Django 3.2.5 on 2021-10-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0002_auto_20211029_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceeding',
            name='type',
            field=models.CharField(max_length=100, verbose_name='tipo'),
        ),
    ]
