# Generated by Django 3.2.5 on 2021-10-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0003_alter_legalrecord_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalrecord',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de conclusión'),
        ),
    ]
