# Generated by Django 3.2.5 on 2021-10-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juris', '0004_alter_legalrecord_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identity_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='cédula de identidad'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('LE', 'Legal'), ('NA', 'Natural')], default='NA', max_length=2, verbose_name='tipo de persona'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('person', 'legal_record')},
        ),
    ]
